module.exports = {
    GET_TOP_APPLICATIONS: 'GET_TOP_APPLICATIONS',       //application actions
    GET_APPLICATIONS: 'GET_APPLICATIONS',
    GET_APPLICATION : 'GET_APPLICATION',
    DOWNLOAD_APPLICATION: 'DOWNLOAD_APPLICATION',
    UPLOAD_APPLICATION: 'UPLOAD_APPLICATION',
    UPLOAD_WITH_ERRORS: 'UPLOAD_WITH_ERRORS',

    LOGIN: 'LOGIN',                                     //profile actions
    SIGN_UP: 'SIGN_UP',
    LOGOUT: 'LOGOUT',
    SHOW_LOGIN: 'SHOW_LOGIN',
    SHOW_SIGN_UP: 'SHOW_SIGN_UP'

};
