module.exports = {
    GET_TOP_APPLICATIONS: 'GET_TOP_APPLICATIONS',       //application actions
    GET_APPLICATIONS: 'GET_APPLICATIONS',
    GET_APPLICATION : 'GET_APPLICATION',
    DOWNLOAD_APPLICATION: 'DOWNLOAD_APPLICATION',
    UPLOAD_APPLICATION: 'UPLOAD_APPLICATION',
    UPLOAD_WITH_ERRORS: 'UPLOAD_WITH_ERRORS',
    GET_DOWNLOADS_APP: 'GET_DOWNLOADS_APP',
    'RATE_APPLICATION': 'RATE_APPLICATION',

    LOGIN: 'LOGIN',                                     //profile actions
    SIGN_UP: 'SIGN_UP',
    LOGOUT: 'LOGOUT',
    SHOW_LOGIN: 'SHOW_LOGIN',
    SHOW_SIGN_UP: 'SHOW_SIGN_UP',
    GET_DOWNLOADS: 'GET_DOWNLOADS',
    TO_DOWNLOADS: 'TO_DOWNLOADS'

};
